### ISSUE TITLE
year is not defined

### ISSUE THREAD

**Issue by jamen** [generate/generate-license#7]
```
[master●] % gen license
[03:56:28] starting generate
[03:56:29] ✔ running tasks: [ 'license' ]
[03:56:29] starting license 
[03:56:29] starting license:default task 
[03:56:29] starting license:license task 
[03:56:29] starting license 
[03:56:29] starting license:choose task 
? Choose the license to generate license-mit
[03:56:31] starting license 
{ ReferenceError: year is not defined
    at eval (engine.templateSources[1]:9:11)
    at renderSync (/home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate-license/node_modules/engine-base/index.js:135:12)
    at render (/home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate-license/node_modules/engine-base/index.js:173:14)
    at /home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate/node_modules/engine-cache/index.js:244:7
    at Object.engineRender [as render] (/home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate/node_modules/engine-cache/index.js:280:7)
    at /home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate/node_modules/templates/lib/plugins/render.js:313:16
    at /home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate/node_modules/base-routes/index.js:168:9
    at /home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate/node_modules/base-routes/index.js:168:9
    at /home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate/node_modules/en-route/lib/index.js:576:15
    at next (/home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate/node_modules/en-route/lib/index.js:161:14)
  files: [ <File "LICENSE" <Buffer 54 68 65 20 4d 49 54 20 4c 69 63 65 6e 73 65 20 28 4d 49 54 29 0a 0a 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 3c 25 3d 20 79 65 61 72 20 25 3e 20 3c ... >> ],
  handled: [ <File "LICENSE" <Buffer 54 68 65 20 4d 49 54 20 4c 69 63 65 6e 73 65 20 28 4d 49 54 29 0a 0a 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 3c 25 3d 20 79 65 61 72 20 25 3e 20 3c ... >> ],
  view: <File "LICENSE" <Buffer 54 68 65 20 4d 49 54 20 4c 69 63 65 6e 73 65 20 28 4d 49 54 29 0a 0a 43 6f 70 79 72 69 67 68 74 20 28 63 29 20 3c 25 3d 20 79 65 61 72 20 25 3e 20 3c ... >>,
  path: '/home/jamen/.nvm/versions/node/v6.5.0/lib/node_modules/generate-license/templates/LICENSE' }
```
After choosing MIT.

**Comment by jonschlinkert** [comment]
related https://github.com/generate/generate/issues/38
